In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
# sentences

sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    "I am a good Developer",
    'understand the meaning of words',
    'I like your videos'
]

In [7]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good Developer',
 'understand the meaning of words',
 'I like your videos']

In [4]:
# initialize the vocabulary size i.e the total number of total possible distinct words present in he whole dataset
voc_size = 10000

### One Hot Representation

In [8]:
one_hot_rep = [one_hot(sentence,voc_size) for sentence in sentences]
one_hot_rep

[[1970, 5534, 9405, 2406],
 [1970, 5534, 9405, 5574],
 [1970, 7430, 9405, 6370],
 [6505, 8373, 8979, 8253, 3670],
 [6505, 8373, 8979, 8253, 2213],
 [6571, 1970, 954, 9405, 1142],
 [6505, 1755, 2325, 8353]]

* DISTINCT WORD HAVE BEEN ENCODED AS SOME FIXED INDEX

#### WORD EMBEDDING REPRESENTATION

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [16]:
max_sent_len = max([len(vec) for vec in one_hot_rep])
embedded = pad_sequences(one_hot_rep,padding='pre',maxlen=max_sent_len)
print(embedded)

[[   0 1970 5534 9405 2406]
 [   0 1970 5534 9405 5574]
 [   0 1970 7430 9405 6370]
 [6505 8373 8979 8253 3670]
 [6505 8373 8979 8253 2213]
 [6571 1970  954 9405 1142]
 [   0 6505 1755 2325 8353]]


In [21]:
# Defining dimensions
dimensions = 10

In [18]:
# creating a model
model = Sequential()
model.add(Embedding(voc_size,dimensions,input_length=max_sent_len))
model.compile("adam","mse")

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 5, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.predict(embedded)

array([[[ 0.03419758,  0.00880586, -0.04496298, -0.01357615,
         -0.03885987,  0.00891455,  0.04709984, -0.02251271,
         -0.04390044,  0.00971903],
        [ 0.00911275,  0.03118452,  0.02816467, -0.01116799,
         -0.0284844 , -0.00571889,  0.03216919,  0.02224169,
          0.00188722,  0.04812031],
        [ 0.00365578, -0.02146312, -0.00435447,  0.02437133,
          0.00541564,  0.00276604, -0.01195568, -0.01672066,
          0.01252807, -0.04089105],
        [-0.04890859,  0.00703826, -0.03444349, -0.04606016,
          0.00440561,  0.04210328,  0.02090294,  0.02904982,
         -0.00676798, -0.01364102],
        [ 0.01239637,  0.02489648,  0.03363669, -0.013582  ,
          0.00962834,  0.02957213,  0.00047253, -0.03704325,
         -0.03649261, -0.00372477]],

       [[ 0.03419758,  0.00880586, -0.04496298, -0.01357615,
         -0.03885987,  0.00891455,  0.04709984, -0.02251271,
         -0.04390044,  0.00971903],
        [ 0.00911275,  0.03118452,  0.02816467, -0